[meta]
name = "Advanced Free Block Mode"
author = "schl3ck"
category = "Map Editor"

siteid = 109
version = "1.3.0"

[game]
min_version = "2021-08-30"

[script]
imports = [ "Icons.as", "Permissions.as" ]
